version: 2
updates:
  - package-ecosystem: composer
    open-pull-requests-limit: 20
    versioning-strategy: increase
    directories:
      - "/"
      - "/tools"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      composer-laminas-dependencies:
        patterns:
          - "laminas/*"
      composer-phpunit-dependencies:
        patterns:
          - "phpunit/*"
          - "spatie/phpunit-snapshot-assertions"
      composer-dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: increase
    directory: "/website"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      npm-docusaurus-dependencies:
        patterns:
          - "@docusaurus/*"
          - "@tsconfig/docusaurus"
          - "clsx"
      npm-react-dependencies:
        patterns:
          - react
          - react-*
          - "@types/react"
          - "@types/react-*"
      npm-dev-dependencies:
        dependency-type: development

  - package-ecosystem: "docker"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
      time: "04:00"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/workflows/actions/**/*"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
