<?php 

$oPaginationControlHelper = $this->plugin('paginationControl');

if ($this->pageCount) {
   

    $aPaginationItems = [];

    // Generate previous link
    if($this->previousLink){
        $aLiAttributes = ['class' => 'page-item'];
        $aPreviousAttributes = ['class' => 'page-link'];
        if(isset($this->previous)){
            $aPreviousAttributes['href'] = $this->url($this->route, ['page' => $this->previous]);
        }
        else{
            $aLiAttributes = $oPaginationControlHelper->setClassesToAttributes($aLiAttributes, ['disabled']);
            $aPreviousAttributes['href'] = '#';
            $aPreviousAttributes['tabindex'] = '-1';
        }

        $aPaginationItems[] = $oPaginationControlHelper->htmlElement(
            'li',
            $aLiAttributes,
            $oPaginationControlHelper->htmlElement(
                'a', 
                $aPreviousAttributes, 
                $this->translate($this->previousLink)
            )
        );
    }

    // Generate pages
    foreach ($this->pagesInRange as $iPage) {

        $aLiAttributes = ['class' => 'page-item'];
        $aLinkAttributes = ['class' => 'page-link'];
        $sLinkContent = $iPage;

        if ($iPage != $this->current) {
            $aLinkAttributes['href'] = $this->url($this->route, ['page' => $iPage]);
        } else {
            $aLiAttributes = $oPaginationControlHelper->setClassesToAttributes($aLiAttributes, ['active']);
            $aLinkAttributes['href'] = '#';
            $sLinkContent .= ' <span class="sr-only">' . $this->translate('(current)') . '</span>';
        }

        $aPaginationItems[] = $oPaginationControlHelper->htmlElement(
            'li',
            $aLiAttributes,
            $oPaginationControlHelper->htmlElement(
                'a', 
                $aLinkAttributes, 
                $this->translate($sLinkContent)
            )
        );
    }

    // Generate next link
    if($this->nextLink){
        $aLiAttributes = ['class' => 'page-item'];
        $aNextAttributes = ['class' => 'page-link'];
        if(isset($this->next)){
            $aNextAttributes['href'] = $this->url($this->route, ['page' => $this->next]);
        }
        else{
            $aLiAttributes = $oPaginationControlHelper->setClassesToAttributes($aLiAttributes, ['disabled']);
            $aNextAttributes['href'] = '#';
            $aNextAttributes['tabindex'] = '-1';
        }

        $aPaginationItems[] = $oPaginationControlHelper->htmlElement(
            'li',
            $aLiAttributes,
            $oPaginationControlHelper->htmlElement(
                'a', 
                $aNextAttributes, 
                $this->translate($this->nextLink)
            )
        );
    }

    $aUlAttributes = ['class' => 'pagination'];
    if($this->size){
        $aUlAttributes = $oPaginationControlHelper->setClassesToAttributes(
            $aUlAttributes, 
            [$oPaginationControlHelper->getSizeClass($this->size, 'pagination')]
        );
    }
    if($this->alignment){
        $aUlAttributes = $oPaginationControlHelper->setClassesToAttributes(
            $aUlAttributes, 
            [$oPaginationControlHelper->getPrefixedClass($this->alignment, 'justify-content')]
        );
    }

    echo $oPaginationControlHelper->htmlElement(
        'nav',
        $this->attributes ?? [],
        $oPaginationControlHelper->htmlElement(
            'ul',
            $aUlAttributes,
            join(PHP_EOL, $aPaginationItems)
        )
    );
}