<?php

$paginationControlHelper = $this->plugin('paginationControl');

if ($this->pageCount) {


    $paginationItems = [];

    // Generate previous link
    if ($this->previousLink) {
        $paginationItems[] = $paginationControlHelper->renderNavigationItem(
            $this->route,
            $this->previousLink,
            $this->previous,
            $this->disabledStates
        );
    }

    // Generate pages
    foreach ($this->pagesInRange as $page) {
        $paginationItems[] = $paginationControlHelper->renderPageItem(
            $this->route,
            $page,
            $this->current,
            $this->activeStates
        );
    }

    // Generate next link
    if ($this->nextLink) {
        $paginationItems[] = $paginationControlHelper->renderNavigationItem(
            $this->route,
            $this->nextLink,
            $this->next,
            $this->disabledStates
        );
    }

    $ulAttributes = $this->htmlattributes(['class' => 'pagination']);
    if ($this->size) {
        $ulAttributes['class']->merge(
            $this->htmlClass()->plugin('size')->getClassesFromOption(
                $this->size,
                'pagination'
            )
        );
    }
    if ($this->alignment) {
        $ulAttributes['class']->merge(
            $this->htmlClass()->plugin('justifyContent')->getClassesFromOption(
                $this->alignment
            )
        );
    }

    echo $this->htmlElement(
        'nav',
        $this->attributes ?? [],
        $this->htmlElement(
            'ul',
            $ulAttributes,
            implode(PHP_EOL, $paginationItems)
        )
    );
}
