on:
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean
    outputs:
      artifact-id:
        description: "The uploaded website build artifact ID"
        value: ${{ jobs.build-website.outputs.artifact-id }}
      artifact-path:
        description: "The uploaded website build artifact path"
        value: ${{ jobs.build-website.outputs.artifact-path }}

jobs:
  generate-phpdoc:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ./website/docs/phpdoc
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-path: ${{ env.ARTIFACT_PATH }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup PHP, with composer and extensions
        uses: ./.github/workflows/actions/setup-php
        with:
          php-version: 8.5

      - name: ♻️ Tools cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: tools/cache
          key: ${{ runner.os }}-tools-${{ matrix.php-versions }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: 📃 Generate PHP documentation
        run: composer generate-phpdoc

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: upload-artifact
        with:
          name: docs-phpdoc
          path: ${{ env.ARTIFACT_PATH }}

  generate-documentation:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ./website/docs
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-path: ${{ env.ARTIFACT_PATH }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup PHP, with composer and extensions
        uses: ./.github/workflows/actions/setup-php
        with:
          php-version: 8.5

      - name: 📃 Generate documentation
        run: composer generate-docs

      - name: 📦 Upload generated documentation artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: upload-artifact
        with:
          name: documentation
          path: ${{ env.ARTIFACT_PATH }}

  build-website:
    needs: [generate-phpdoc, generate-documentation]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      ARTIFACT_PATH: ./website/build
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-path: ${{ env.ARTIFACT_PATH }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          artifact-ids: ${{ needs.generate-phpdoc.outputs.artifact-id }}
          path: ${{ needs.generate-phpdoc.outputs.artifact-path }}

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          artifact-ids: ${{ needs.generate-documentation.outputs.artifact-id }}
          path: ${{ needs.generate-documentation.outputs.artifact-path }}

      - uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@9f77c58db848451f244f78047fbf779c60bb8641 # 0.23.1
        id: setup-node
        with:
          working-directory: website

      - name: ♻️ Webpack cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: website/node_modules/.cache/webpack
          key: ${{ runner.os }}-webpack-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-webpack-

      - name: 🏗️ Build website
        run: ${{ steps.setup-node.outputs.run-script-command }} build
        working-directory: website

      - uses: hoverkraft-tech/ci-github-common/actions/create-and-merge-pull-request@4c9d51717dc04d823dac2dc9ac2857e7b3069454 # 0.35.0
        if: inputs.publish
        with:
          github-token: ${{ github.token }}
          branch: docs/update-website
          title: "docs: update documentation"
          body: |
            Automated documentation update for the website.

            This pull request was created and merged by the website build workflow.

            [skip ci]
          commit-message: "docs: update documentation"

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: artifact-full-path
        env:
          ARTIFACT_PATH: ${{ env.ARTIFACT_PATH }}
        with:
          script: |
            const path = require("node:path");

            const absolutePath = path.resolve(process.env.GITHUB_WORKSPACE, process.env.ARTIFACT_PATH);
            // Add a wildcard to the first folder of the path
            const fullpath = absolutePath.replace(/\/([^/]+)/, '/*$1');

            core.setOutput("path", fullpath);

      - name: 📦 Upload website build artifact
        if: inputs.publish
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: upload-artifact
        with:
          path: ${{ steps.artifact-full-path.outputs.path }}
